config/routes.rb
Rails.application.routes.draw do
  get 'pages/projects'
  get 'pages/resume'
  get 'pages/about'
  get 'pages/interests'
  get 'pages/resume'
  get 'pages/ducky'
  root 'welcome#index'
  get 'welcome/bugs'
  resources :welcome, only: [:index, :new, :create]
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/welcome.rb
class Welcome < MailForm::Base
    attribute :name,      :validate => true
    attribute :email,     :validate => /\A([\w\.%\+\-]+)@([\w\-]+\.)+([\w]{2,})\z/i
    attribute :message
    attribute :nickname,  :captcha  => true
  
    # Declare the e-mail headers. It accepts anything the mail method
    # in ActionMailer accepts.
    def headers
      {
        :subject => "Notice",
        :to => "freshstudiosllc@gmail.com",
        :from => %("#{name}" <#{email}>)
      }
    end
  end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def projects
  end

  def resume
  end

  def about
  end

  def interests
  end

  def resume
    send_file(
      "#{Rails.root}/public/resume.pdf",
      filename: "Tolulope_Oshinowo_Resume.pdf",
      type: "application/pdf"
    )
  end

end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
    def index
        @contact = Welcome.new(params[:welcome])
    end
    
    def create
        @contact = Welcome.new(params[:welcome])
        @contact.request = request
        respond_to do |format|
            if @contact.deliver
                @contact = Welcome.new
                format.html { render 'index'}
                format.js   { flash.now[:success] = @message = "Thank you for your notice. Improvement is key! 😁" }
            else
                format.html { render 'index' }
                format.js   { flash.now[:error] = @message = "Looks like notices are unable to send. 😟" }
            end
        end
    end

    def bugs
        @contact = Welcome.new(params[:welcome])
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <style>
    body {
      padding: 10px;
    }

    * {
      padding: 5px;
    }

    ul.topnav {
      list-style-type: none;
      margin: 0;
      padding: 0;
      overflow: hidden;
      background-color: #333;
    }

    ul.topnav li {float: left;}

    ul.topnav li a {
      display: block;
      color: white;
      text-align: center;
      padding: 14px 16px;
      text-decoration: none;
      font-size: medium;
    }

    ul.topnav li a:hover:not(.active) {background-color: #111;}

    ul.topnav li.right {float: right;}

    @media screen and (max-width: 600px) {
      ul.topnav li.right, 
      ul.topnav li {float: none;}
    }
  </style>
  <head>
    <title>toshinowo.co</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <%= favicon_link_tag asset_path('toshinowo.png') %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>

    <!-- Custom styles for this template -->
    <link href="" rel="stylesheet">
    <ul class="topnav">
      <li class="acive"><%= link_to "toshinowo.co", root_path %></li>
      <li><%= link_to "projects", pages_projects_path %></li>
      <li><%= link_to "interests", pages_interests_path %></li>
      <li class="right"><%= link_to "about", pages_about_path %></li>
    </ul>
  </head>

  <body>
    <%= yield %>
    <footer class="footer text-faded text-center py-5">
      <div class="container">
        <p class="m-0 small">toshinowo.co &copy; 2022</p>
        <h6 style="font-style: italic"><%= link_to "bugs?", welcome_bugs_path %></h6>
      </div>
    </footer>
  </body>
</html>

app/views/pages/about.html.erb
<body>
<style>
 * { padding: 5px; }
</style>
<div style="text-align: center;">

<h1 style="font-style: italic">about</h1>
<span><%= image_tag("div4.png", :alt => "div4", :size => '50x50')%></span>

<h4>Synopsis:</h4>
<p style="text-size: large; padding-left: 30%; padding-right: 30%;">
Ever since I was little, I was obsessed with learning, and throughout my life,
I have developed a strong set of technical skills that have matched my drive to
always learn. For example, I thought myself Java in 7th grade, and since then I
have also become proficient in C# and JavaScript; languages that I have used to
develop mobile apps. I am currently a student at Olin College of Engineering
majoring in Computer and Electrical Engineering.
<br/>
<br/>
Keeping in step with my desire for knowledge, I have also coupled the concepts
that I learned during my first year at Olin in Python to teach myself Django web
development, Rails web development, and the MERN stack—among other new skills
like utilizing Google Cloud, Heroku, and Azure.
<br/>
<br/>
From my second year I was able to delve deeper into the logic and structures of
computing, using tools like Verilog, C and various build environments along the
way. Additionally I took the time to self study blockchain technology and
recently released my own cryptocurrency.
<br/>
<br/>
During my third year I learned more about firmware through C++ and was able to build
upon my web development skills withe React along with decentralized app development
within the Ethereum/Polygon ecosystems with Solidity and Web3JS. I also gained further
exposure into the music industry and was able to launch a startup focused on empowering
independent artists monetize their passions through NFT's.
<br/>
<br/>
So far this year has consisted of synthesizing everything I have learned from school,
personal projects, and industry to give back. I recently have launched a fellowship
program in which up to $100 is given to high school students from disadvantaged backgrounds.
</p>

<h4>Resources:</h4>
<p><%= image_tag("linkedin.png", :alt => "linkedin icon", :size => '24x24')%><a href="https://www.linkedin.com/in/tolulope-oshinowo-145582193/"> LinkedIn</a></p>
<p><%= image_tag("github.png", :alt => "github icon", :size => '24x24')%><a href="https://github.com/toluooshy"> GitHub</a></p>
<p><%= image_tag("resume.png", :alt => "papers", :size => '24x24')%><%= link_to " Resume", "resume.pdf" %></p>
</div>
</body>

app/views/pages/ducky.html.erb
<!DOCTYPE html>
<html>
<head>
<meta name="viewport" content="width=device-width, initial-scale=1.0"/>
<style>
canvas {
    border:1px solid #fefefe;
    background-color: #45b6fe;
}
h1 {text-align: center;}
p {text-align: center;}
div {text-align: center; }
canvas { margin: auto; display: block;}
head {
    height: 0px;
}
ul.topnav {
    height: 0px;
    list-style-type: none;
    margin: 0;
    padding: 0;
    overflow: hidden;
    background-color: #333;
}

ul.topnav li {float: left;}

ul.topnav li a {
    display: block;
    color: white;
    text-align: center;
    padding: 14px 16px;
    text-decoration: none;
    font-size: medium;
}

ul.topnav li a:hover:not(.active) {background-color: #111;}

ul.topnav li.right {float: right;}

@media screen and (max-width: 600px) {
    ul.topnav li.right, 
    ul.topnav li {float: none;}
}

</style>
</head>

<div>
<body onload="startGame()">
<script>
var myGamePiece1, myGamePiece2, myGamePiece3, myGamePiece4, myGamePiece5;
var myObstacles = [];
var myScore;
var frame = 100

function startGame() {
    myGamePiece1 = new component(10, 10, "orange", 115, 320);
    myGamePiece2 = new component(30, 30, "gray", 105, 330);
    myGamePiece3 = new component(25, 40, "#cfb997", 107.5, 330);
    myGamePiece4 = new component(22, 16, "#003300", 109, 330);
    myGamePiece5 = new component(20, 20, "green", 110, 325);
    myScore = new component("30px", "Arial", "white", 10, 35, "text");
    myGameArea.start();
}

var myGameArea = {
    canvas : document.createElement("canvas"),
    start : function() {
        this.canvas.width = 270;
        this.canvas.height = 380;
        this.context = this.canvas.getContext("2d");
        document.body.insertBefore(this.canvas, document.body.childNodes[0]);
        this.frameNo = 0;
        this.interval = setInterval(updateGameArea, 20);
        },
    clear : function() {
        this.context.clearRect(0, 0, this.canvas.width, this.canvas.height);
    }
}

function component(width, height, color, x, y, type) {
    this.type = type;
    this.score = 0;
    this.width = width;
    this.height = height;
    this.speedX = 0;
    this.speedY = 0;    
    this.x = x;
    this.y = y;
    this.gravity = 0;
    this.horizontalSpeed = 0;
    this.baseImage = new Image();
    this.baseImage.onload = function() {
	context.drawImage(baseImage, 0, 0);
    }
    this.update = function() {
        ctx = myGameArea.context;
        if (this.type == "text") {
            ctx.font = this.width + " " + this.height;
            ctx.fillStyle = color;
            ctx.fillText(this.text, this.x, this.y);
        } else {
            ctx.fillStyle = color;
            ctx.fillRect(this.x, this.y, this.width, this.height);
        }
    }
    this.newPos = function() {
        this.gravitySpeed += this.gravity;
        this.x += this.speedX + this.horizontalSpeed;
        this.y += this.speedY;
        this.hitBottom();
    }
    this.hitBottom = function() {
        var rockbottom = myGameArea.canvas.height - this.height;
        if (this.y > rockbottom) {
            this.y = rockbottom;
            this.gravitySpeed = 0;
        }
    }
    this.crashWith = function(otherobj) {
        var myleft = this.x;
        var myright = this.x + (this.width);
        var mytop = this.y;
        var mybottom = this.y + (this.height);
        var otherleft = otherobj.x;
        var otherright = otherobj.x + (otherobj.width);
        var othertop = otherobj.y;
        var otherbottom = otherobj.y + (otherobj.height);
        var crash = true;
        if ((mybottom < othertop) || (mytop > otherbottom) || (myright < otherleft) || (myleft > otherright)) {
            crash = false;
        }
        return crash;
    }
}

function updateGameArea() {
    var x, height, gap, minHeight, maxHeight, minGap, maxGap;
    for (i = 0; i < myObstacles.length; i += 1) {
        if (myGamePiece1.crashWith(myObstacles[i])) { return; } 
	if (myGamePiece2.crashWith(myObstacles[i])) { return; } 
	if (myGamePiece3.crashWith(myObstacles[i])) { return; } 
	if (myGamePiece4.crashWith(myObstacles[i])) { return; } 
	if (myGamePiece5.crashWith(myObstacles[i])) { return; } 
    }
    myGameArea.clear();
    myGameArea.frameNo += 1;
    if (myGameArea.frameNo == 1 || everyinterval(150)) {
        x = myGameArea.canvas.width;
        minWidth = 50;
        maxWidth = 150;
        width = Math.floor(Math.random()*(maxWidth-minWidth+1)+minWidth);
        minGap = 50;
        maxGap = 100;
        gap = Math.floor(Math.random()*(maxGap-minGap+1)+minGap);
        myObstacles.push(new component(x - width - gap, 35, "#3c280d", 0, 0));
	myObstacles.push(new component(10, 35, "tan", x - width - gap, 0));
	myObstacles.push(new component(15, 20, "tan", x - width - gap - 2.5, 7.5));
        myObstacles.push(new component(width + 50, 35, "#3c280d", x - gap, 0));
	myObstacles.push(new component(10, 35, "tan", x - gap, 0));
	myObstacles.push(new component(15, 20, "tan", x - gap - 2.5, 7.5));	
    }
    for (i = 0; i < myObstacles.length; i += 1) {
        myObstacles[i].y += 1.0000001;
        myObstacles[i].update();
    }
    myScore.text = Math.floor(myGameArea.frameNo/5);
    myScore.update();
    myGamePiece1.newPos(); myGamePiece1.update();
    myGamePiece2.newPos(); myGamePiece2.update();
    myGamePiece3.newPos(); myGamePiece3.update();
    myGamePiece4.newPos(); myGamePiece4.update();
    myGamePiece5.newPos(); myGamePiece5.update();
}

function everyinterval(n) {
    if ((myGameArea.frameNo / n) % 1 == 0) {return true;}
    return false;
}

function move(n) {
    myGamePiece1.horizontalSpeed = n;
    myGamePiece2.horizontalSpeed = n;
    myGamePiece3.horizontalSpeed = n;
    myGamePiece4.horizontalSpeed = n;
    myGamePiece5.horizontalSpeed = n;
}
</script>
</br>
<h1>Ducky</h1>
<button style="margin-right: 25px; color: black" onmousedown="move(-1.5)" onmouseup="move(0)" ontouchstart="move(-1.5)" ontouchend="move(0)"><</button>
<button style="margin-left: 25px; color: black" onmousedown="move(1.5)" onmouseup="move(0)" ontouchstart="move(1.5)" ontouchend="move(0)">></button>
<p>
    Hey you found a secret feature! Good job!
    <br/>
    <%= link_to "back", welcome_bugs_path %>
</p>

<pre>
You Are Ducky. 🦆
Navigate Waters. 🌊
Score Big! 🎰
</pre>
</div>
</body>
</html>

app/views/pages/interests.html.erb
<body>
<style>
 * { padding: 5px; }
</style>
<div style="text-align: center;">

<h1 style="font-style: italic">interests</h1>
<span><%= image_tag("div3.png", :alt => "div3", :size => '50x50')%></span>

<h4>Synopsis:</h4>
<p style="text-size: large; padding-left: 20%; padding-right: 20%;">
For a long time, whenever I experienced something interesting I would try 
recreate it in my own special ways. For example, my love of the ‘Garfield’ 
comic series saw me creating my own comics that I shared with my classmates 
(I even convinced my 5th grade teacher to allow me to read them aloud to 
the class during reading time). When my parents finally agreed to the idea 
of cable television, it was only a matter of time for me to start animating 
my comics using MS Paint and Windows Movie Maker after watching Cartoon Network. 
In middle school, I, like most boys of my age, loved video games, and in suit 
I taught myself how to make games, a hobby I still enjoy to this day. 
Similarly, my fascination in electronic and techno music, coupled with my 
musical background (mainly Clarinet, Viola, and some Guitar), led me to start 
producing my own beats. My desire to create has always been a beacon for me, 
and has helped molded me into who I am today, who I will be tomorrow, and beyond. 
Enjoy a few samples of what I’ve been producing!
<br/>
<br/>
These days my desire for creating tolerant dialogues and working towards a more 
socially just landscape has led me to make appearances at panels and presentations 
concerned about creating more ethical and equitable environments.
<br/>
<a href="https://www.youtube.com/watch?v=jxY3ISDaD7Y">Climate Strike (2019)</a> | <a href="https://github.com/toluooshy">Imagining Inclusive, Diverse, and Equitable Futures of Work (2020)</a>
<br/>
</p>

<h4>Beats:</h4>
<p><%= image_tag("gdrive.png", :alt => "google drive icon", :size => '24x24')%><a href="https://drive.google.com/file/d/1_RLSyU69EhQ9xfTfsI55AJfD65OQHKGx/view?usp=sharing"> Tempo</a></p>
<p><%= image_tag("gdrive.png", :alt => "google drive icon", :size => '24x24')%><a href="https://drive.google.com/file/d/1jxvIi6asilzAjfOQjJauxUZB2kPzqEU4/view?usp=sharing"> Voyager</a></p>
<p><%= image_tag("gdrive.png", :alt => "google drive icon", :size => '24x24')%><a href="https://drive.google.com/file/d/160BKagStTAYY1fKqJmBo6DRqS46ueNms/view?usp=sharing"> 23Y</a></p>
</div>
</body>

app/views/pages/projects.html.erb
<body>
<style>
 * { padding: 5px; }
</style>

<div style="text-align: center;">

<h1 style="font-style: italic">projects</h1>
<span><%= image_tag("div2.png", :alt => "div2", :size => '50x50')%></span>
</br>
<h4>Current And Past Projects:</h4>
</br>
<h3><mark><a href="https://nft.coinbase.com/collection/ethereum/0xa53a0a7523c3ac6db07d5761a8e5e365f87c752b"> Summer 2022 Crytern NFT</a></mark></h3>
<p style="text-size: large; padding-left: 15%; padding-right: 15%;">
This summer we had our largest cohort of crypterns yet, hailing from all 🌎 over 🌍 the
🌏 globe! It's been a long winding summer, and we (the Summer 2022 Cryptern Social
Committee) wanted to present to you a token of congratulations. 🥳
<br/>
<%= image_tag("summer2022crypternnft.png", :alt => "summer 2022 cryptern nft collection", :size => '683x300')%>
<br/>
This decentralized app, or "dapp" was created with ReactJS, Web3JS, and Solidity; hosted internally.
<br/>
</p>

</br>
</br>

<h3><mark><a href="https://www.kairosmusic.io/"> Kairos Music</a></mark></h3>
<p style="text-size: large; padding-left: 15%; padding-right: 15%;">
Founded in February 2021, Kairos MGMT was originally a “full-service NFT management Agency
made for the Music Industry” that guided artists who wanted to break into blockchain. Our
startup is named after Caerus from Greek Myth, the personification of being at the right
time and place, because of how quickly we grew. After several discussions with independent
artists and music management companies, we realized that there was a lack of blockchain
education and accessibility to blockchain technology in the music industry—we felt keeping
our material behind a paywall would exacerbate the inaccessibility of blockchain adoption.
While we enjoyed growing with our artists and their teams, pivoting our focus from
personalized guidance to fostering an educational community felt more aligned with our
mission to lower the barrier to entry in the blockchain industry.

We are made in Massachusetts and New York with love ❤️
<br/>
<%= image_tag("kairosmusic.png", :alt => "summer 2022 cryptern nft collection", :size => '683x300')%>
<br/>
This startup was developed, with ReactJS, NodeJS, VanillaJS, Web3JS, and Solidity; hosted on AWS.
<br/>
</p>

</br>
</br>

<h3><mark><a href="https://sites.google.com/view/signalsolver/home"> Signal Solver</a></mark></h3>
<p style="text-size: large; padding-left: 15%; padding-right: 15%;">
The world of analog and digital communications builds upon the fundamentals of how
signal systems work. This means that just like in signal systems, sinusoidal, domain
shifting, and other combinatorial operations make a return here. This minigame attempts
to take theoretical signal operations and incorpotate them into a multi-challenge based
educational experince that is both comprehensive and intuitive.
<br/>
<%= image_tag("signalsolver.gif", :alt => "signal solver demo gif", :size => '683x613')%>
<br/>
This minigame was created with HTML and VanillaJS.
<br/>
</p>

</br>
</br>

<h3><mark><a href="https://olincollege.github.io/pie-2021-03/Cup-Noodle/"> The Cup Noodle Machine</a></mark></h3>
<p style="text-size: large; padding-left: 15%; padding-right: 15%;">
The Cup Noodle Ramen Vending Machine is a creation made to make the simple things even
simpler. See your ramen being made right before your eyes by using our app to place an
order from one of our selection sliders. Our vending machine houses a two-axis gantry
system that can deliver your choice of four ramen flavors, as well as hot water, and can
provide ramen ready for you to enjoy. Our goal for this project was to build an aesthetically
pleasing method of dispensing ready-to-eat cup ramen to customers. We hoped to create
something mechanically innovative with extensive modulability, allowing for customer
customization. Our vending machine features a kettle for hot water dispensing, four cup
ramen dispensers, a large gantry system, and wooden housing that still allows customers
to witness the mechanical processes within our machine. Our website gives many customization
options for ramen flavors and toppings and allows for a lot of customer interactivity. 
<br/>
<iframe width="683" height="366" src="https://www.youtube.com/embed/6TkAAt8hxeA" title="Cup Noodle Product Video - Principles of Integrated Engineering @ Olin College" frameborder="0" allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture" allowfullscreen></iframe>
<br/>
This project was created with a ReactJS webapp hosted on Heroku; with FastAPI interactivity, Arduino/C++ firmware, and hardware spanning woods, plastics, and metals.
<br/>
</p>

</br>
</br>

<h3><mark><a href="http://www.wobblefinance.com/"> Wobble Finance</a></mark></h3>
<p style="text-size: large; padding-left: 15%; padding-right: 15%;">
Wobble Finance is a bare-bones cryptocurrency screener that allows the user to look
up hundreds of different cryptocurrencies and see how they are performing. Simply
search for any major cryptocurrency symbol and in seconds get the bread-and-butter
statistics about it, including the current price, the 24-hour price change, and the
total exchange volume in USD. Wobble Finance was created to help those new to the
cryptocurrency space learn more about cryptocurrencies through educational videos
and then apply what they have learned with the aid of the Wobble Finance screener
web app. In addition to this there is the Wobble Finance Token (WBBL) that helps
fund API calls for the web app. The Wobble Finance Token (WBBL) is available to trade
on the Binance Smart Chain as a BEP-20 token and is a listed asset on PancakeSwap.
<br/>
<%= image_tag("wobblefinance.gif", :alt => "wobble finance demo gif", :size => '683x300')%>
<br/>
This webapp was created with NodeJS, EJS, and Solidity; hosted on Heroku.
<br/>
</p>

</br>
</br>

<h3><mark><a href="https://hipstertrek.herokuapp.com/"> HipsterTrek</a></mark></h3>
<p style="text-size: large; padding-left: 15%; padding-right: 15%;">
Over the past few decades we have seen the global music industry evolve at continuously
increasing rates, and with this phenomenon comes the advent of music becoming more
accessible to individuals overall. Just like how no two people share the exact same
character traits, our music tastes vary from person to person as well. This notion had
me thinking about different major music genres and how it could be possible to find
similarities between them and create a basic graphical representation. In the process
of creating this map one question began to rise in my mind: could it be possible to
create an algorithm that would offer the shortest path to go from one music genre to
another? This became the basis for my implementation project.
<br/>
<%= image_tag("hipstertrek.gif", :alt => "hipstertrek demo gif", :size => '683x300')%>
<br/>
This webapp was created with NodeJS, EJS, and VanillaJS; hosted on Heroku.
<br/>
</p>

</br>
</br>

<h3><mark><a href="https://toluooshy.github.io/SoftSysDynamiChat/"> DynamiChat</a></mark></h3>
<p style="text-size: large; padding-left: 15%; padding-right: 15%;">
The ultimate goal of DynamiChat is to serve as a messaging platform that can be accessed
simply from the user’s terminal with an internet connection, allowing for a more streamlined
and simplistic medium of communication. Starting with internet communications, a MongoDB Atlas
cluster was set up to hold the data from messages sent and received, and DyanmiChat would
communicate with this database using GET and POST requests written in C with the MongoDB C Driver.
<br/>
<%= image_tag("dynamichat.gif", :alt => "dynamichat demo gif", :size => '683x328')%>
<br/>
This application was created with C, BSON, and Shell Script; data is stored and managed with MongoDB.
<br/>
</p>

</br>
</br>

<h3><mark><a href="http://www.fitpic.co/"> fitpic</a></mark></h3>
<p style="text-size: large; padding-left: 15%; padding-right: 15%;">
This project was designed to be a "virtual closet" where the user can log any 
clothing attire they might have hat they would like to try something new with; 
all the while promoting sustainable/ethical clothing brands. Currently this 
project is under redesign to allow the user to log in (previously this was 
an offline webapp).
<br/>
<%= image_tag("fitpicweb.png", :alt => "fitpic screenshot", :size => '683x384')%>
<br/>
This webapp was created with Python, Django, and SQLite/PostgreSQL; hosted on Heroku.
<br/>
</p>

</br>
</br>

<h3><mark><a href="http://thesbpro.org/"> The Storyboard Project</a></mark></h3>
<p style="text-size: large; padding-left: 15%; padding-right: 15%;">
This project was designed to be a "coming-of-age" platform for young adults to 
semi-anonymously submit vignettes from their childhoods through adolescence. This 
was developed in hopes of spurring conversation around overlooked conversations 
that could be had, and can be used by parents to better understand what their 
children may be going through from the mouth of another youth. 
<br/>
<%= image_tag("storyboardweb.png", :alt => "the storyboard project screenshot", :size => '683x384')%>
<br/>
This webapp was created with NodeJS, Axios, and Firebase/Firestore; hosted on Firebase.
<br/>
</p>

</br>
</br>

<h3><mark><a href="https://sd2020spring.github.io/PyRacer-The-Game/"> PyRacer</a></mark></h3>
<p style="text-size: large; padding-left: 15%; padding-right: 15%;">
This Python game is a modern adaptation of the classic SEGA game ‘Outrun’, 
with a remix to the original game play where you can choose between three 
different cars and race along 6 different courses. It was developed as my  
final project for my Software Design class at Olin.
<br/>
<%= image_tag("pyracer.gif", :alt => "pyracer gameplay teaser", :size => '683x384')%>
<br/>
This game was created with Python and Pygame.
<br/>
</p>

</br>
</br>

<p><%= image_tag("github.png", :alt => "github icon", :size => '64x64')%><a href="https://github.com/toluooshy"> <h2><i>For more cool projects check out my GitHub profile!</i></h2></a></p>

</div>
</body>

app/views/pages/resume.html.erb
<h1>Pages#resume</h1>
<p>Find me in app/views/pages/resume.html.erb</p>

app/views/welcome/_contact_form.html.erb
<%= form_for @contact, url: welcome_index_path, remote: true do |f| %>
    <div class="col-md-12">
        <%= f.label :name %></br>
        <%= f.text_field  :name, required: true, class: "contact-form-text-area" %></br>

        <%= f.label :email %></br>
        <%= f.text_field :email, required: true, class: "contact-form-text-area" %></br>

        <%= f.label :message %></br>
        <%= f.text_area :message, rows: 8, cols: 40, required: true, class: "contact-form-text-area",
                        placeholder: "Send me a message"%></br>

        <div class= "hidden">
            <%= f.label :nickname %>
            <%= f.text_field :nickname, :hint => 'Leave this field blank!' %>
        </div>
        
        <br/>
        <%= f.submit 'Send Message', class: 'btn btn-primary' %>
    </div>
  <% end %>
  <div class="col-md-12" id="flash-message">
    <%= render 'flash' %>
  </div>

app/views/welcome/_flash.html.erb
<% flash.each do |message_type, message| %>
    <%= content_tag(:div, message, class: "alert alert-#{message_type}") %>
<% end %>

app/views/welcome/bugs.html.erb
<body>
<div style="text-align: center;">

<h1 style="font-style: italic">contact/bug tracker</h1>
<span><%= image_tag("div1.png", :alt => "div1", :size => '50x50')%></span>

<h4>Synopsis:</h4>
<p style="text-size: large; padding-left: 30%; padding-right: 30%;">
This page is meant to serve as a way to contact me. Additionally, if you happen   
to try out any of my featured projects on GitHub and run into issues this page 
doubles as a portal to notify me of bugs that require fixing. These can be 
anything from spelling/grammatical errors to fundamental coding flaws that lower 
performance or hinder usability. All critiques are welcome! <%= link_to "🦆", pages_ducky_path %>
<br/>
<div>
    <%= render 'contact_form' %>
</div>
<br/>
</p>

</div>
</body>

app/views/welcome/create.js.erb
// Render flash message
$('#contact').html("<%= j render 'contact_form' %>");
$('#flash-message').html("<%= j render 'flash' %>").delay(3000).fadeOut(4000);